# SPDX-FileCopyrightText: 2025, FANUC America Corporation
# SPDX-FileCopyrightText: 2025, FANUC CORPORATION
#
# SPDX-License-Identifier: Apache-2.0

# Joint limits for CRX-10iA and CRX-10iA/L

# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  J1:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: true
    max_acceleration: 0.4
  J2:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: true
    max_acceleration: 0.4
  J3:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 0.4
  J4:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 1.0
  J5:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 1.0
  J6:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 1.0
